from sqlalchemy import Column, Integer, String, Float, DateTime, JSON, Text
from sqlalchemy.sql import func
from authentication.database import Base


class VoiceAnalysisReport(Base):
    __tablename__ = "voice_analysis_reports"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String(200), nullable=False, unique=True, index=True)
    application_id = Column(Integer, nullable=True, index=True)

    # Prosody metrics (librosa)
    wpm = Column(Float, nullable=True)                  # words per minute
    pause_count = Column(Integer, nullable=True)        # number of significant pauses
    filler_count = Column(Integer, nullable=True)       # um/uh/like/you know
    pitch_variance = Column(Float, nullable=True)       # std dev of pitch in Hz
    volume_stability = Column(Float, nullable=True)     # 0-1 score

    # Linguistic metrics (GPT-4o)
    linguistic_score = Column(Float, nullable=True)     # 0-100
    answer_completeness = Column(Float, nullable=True)
    star_structure_score = Column(Float, nullable=True)
    vocabulary_richness = Column(Float, nullable=True)
    hedging_ratio = Column(Float, nullable=True)
    deflection_count = Column(Integer, nullable=True)

    # Combined
    confidence_index = Column(Float, nullable=True)     # 0-100
    recommendation = Column(String(50), nullable=True)  # Confident | Neutral | Needs Review

    # Detailed breakdowns (JSON)
    per_question_scores = Column(JSON, nullable=True)
    flagged_moments = Column(JSON, nullable=True)       # [{timestamp, reason, text}]

    # Full transcript (if generated by whisper)
    transcript = Column(Text, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
